server:
  port: 8801
spring:
  profiles:
    active: dev
  application:
    name: doctor-server
  datasource:
    url: jdbc:mysql://192.168.1.221:3306/pra
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    discovery:
      enabled: true
      serviceId: eureka-server

  redis:
  #################redis基础配置#################
    database: 8
    host: 192.168.0.63
    password:
    port: 6379
    timeout: 5000
  #################redis线程池设置#################
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000

eureka:
  client:
    serviceUrl:
      defaultZone:  http://192.168.1.222:8888/eureka/


feign:
  hystrix:
    enabled: true

# mybatis
mybatis:
  mapper-locations:  classpath:mapping/*/*.xml
  type-aliases-package: com.prostate.*.entity
